Param(
  [string]$ProjectRoot = "D:\git\criminalminds2"
)
$ErrorActionPreference = "Stop"
$keysPath = Join-Path $ProjectRoot "api-keys.json"
if (Test-Path $keysPath) {
  try {
    $keys = Get-Content -Raw -Path $keysPath | ConvertFrom-Json
    if ($keys.elevenlabsApiKey) { $env:ELEVENLABS_API_KEY = $keys.elevenlabsApiKey }
  } catch {}
}
if (-not $env:ELEVENLABS_API_KEY -or $env:ELEVENLABS_API_KEY.Trim().Length -eq 0) {
  Write-Output "NO_KEY"
  exit 2
}
$headers = @{ "xi-api-key" = $env:ELEVENLABS_API_KEY }
try {
  $voicesResp = Invoke-RestMethod -Method Get -Uri "https://api.elevenlabs.io/v1/voices" -Headers $headers
} catch {
  Write-Output ("VOICES_ERR " + $_.Exception.Message)
  exit 3
}
$voice = $voicesResp.voices | Select-Object -First 1
if (-not $voice) {
  Write-Output "NO_VOICES"
  exit 4
}
$voiceId = $voice.voice_id
$body = @{
  text = "This is a quick audio test generated by ElevenLabs."
  model_id = "eleven_multilingual_v2"
  voice_settings = @{ stability = 0.5; similarity_boost = 0.75 }
  output_format = "mp3_44100_128"
} | ConvertTo-Json
$outFile = Join-Path $ProjectRoot "tts_test.mp3"
try {
  Invoke-WebRequest -Method Post -Uri ("https://api.elevenlabs.io/v1/text-to-speech/" + $voiceId) -Headers ($headers + @{ "Accept"="audio/mpeg"; "Content-Type"="application/json" }) -Body $body -OutFile $outFile
} catch {
  Write-Output ("TTS_ERR " + $_.Exception.Message)
  exit 5
}
if (Test-Path $outFile) {
  Start-Process $outFile | Out-Null
  Write-Output ("OK " + $voiceId + " " + $outFile)
  exit 0
} else {
  Write-Output "NO_FILE"
  exit 6
}
